import { Product } from "./types";

export const merchant = { id: "m_demo", name: "Nila Everyday", category: "Wellness & lifestyle" };

export const products: Product[] = [
  { id: "p_cleanser", sku: "NIL-CLN-100", name: "Calm Cloud Cleanser", description: "A gentle, fragrance-free daily gel cleanser for reactive and sensitive skin.", category: "skincare", pricePaise: 59900, compareAtPaise: 69900, costPaise: 22000, inventory: 42, tags: ["sensitive-skin", "fragrance-free", "cleanser"], attributes: { fragrance: "none", skin: "sensitive", size: "100 ml" }, image: "◌", crossSellIds: ["p_moisturizer", "p_spf"], subscriptionEligible: true, available: true },
  { id: "p_moisturizer", sku: "NIL-MOI-050", name: "Barrier Repair Moisturizer", description: "Ceramide moisturizer that pairs with a gentle cleanser; no added fragrance.", category: "skincare", pricePaise: 89900, compareAtPaise: 99900, costPaise: 35000, inventory: 28, tags: ["sensitive-skin", "fragrance-free", "ceramide"], attributes: { fragrance: "none", skin: "sensitive", size: "50 g" }, image: "✦", crossSellIds: ["p_cleanser", "p_spf"], subscriptionEligible: true, available: true },
  { id: "p_spf", sku: "NIL-SPF-050", name: "Daily Mineral SPF 50", description: "Sheer mineral sunscreen formulated for sensitive skin, fragrance free.", category: "skincare", pricePaise: 74900, costPaise: 30000, inventory: 19, tags: ["sensitive-skin", "fragrance-free", "sunscreen"], attributes: { fragrance: "none", spf: "50", skin: "sensitive" }, image: "☀", crossSellIds: ["p_cleanser", "p_moisturizer"], subscriptionEligible: true, available: true },
  { id: "p_coffee", sku: "NIL-COF-250", name: "Monsoon Estate Coffee", description: "Medium roast whole-bean coffee with cocoa and citrus notes.", category: "pantry", pricePaise: 64900, costPaise: 26000, inventory: 70, tags: ["coffee", "monthly", "whole-bean"], attributes: { roast: "medium", size: "250 g" }, image: "◒", crossSellIds: ["p_filter"], subscriptionEligible: true, available: true },
  { id: "p_filter", sku: "NIL-FIL-01", name: "Steel Pour-over Filter", description: "Reusable stainless-steel dripper compatible with standard mugs.", category: "accessories", pricePaise: 39900, costPaise: 11000, inventory: 36, tags: ["coffee", "compatible", "reusable"], attributes: { compatibleWith: "coffee" }, image: "⌁", crossSellIds: ["p_coffee"], subscriptionEligible: false, available: true },
  { id: "p_gift", sku: "NIL-GFT-01", name: "Care Gift Box", description: "A ready-to-gift box with an unscented candle and a handwritten note.", category: "gifts", pricePaise: 79900, costPaise: 30000, inventory: 25, tags: ["gift", "team", "under-1000"], attributes: { giftWrap: "included" }, image: "◇", crossSellIds: ["p_gift_note"], subscriptionEligible: false, available: true },
  { id: "p_gift_note", sku: "NIL-GFT-NOTE", name: "Premium Message Card", description: "A textured recycled-stock card with a merchant-personalized message.", category: "gifts", pricePaise: 9900, costPaise: 1800, inventory: 120, tags: ["gift", "team", "personalized"], attributes: { paper: "recycled", personalization: "included" }, image: "✎", crossSellIds: ["p_gift"], subscriptionEligible: false, available: true },
  { id: "p_runner", sku: "NIL-RUN-01", name: "Cloudstep Daily Trainer", description: "Neutral cushioned running shoes for daily 5K training and easy miles.", category: "running", pricePaise: 329900, compareAtPaise: 379900, costPaise: 174000, inventory: 18, tags: ["running", "shoes", "neutral", "daily-trainer", "primary"], attributes: { terrain: "road", support: "neutral", weight: "248 g" }, image: "↗", crossSellIds: ["p_socks", "p_bottle", "p_belt"], subscriptionEligible: false, available: true },
  { id: "p_socks", sku: "NIL-RUN-SOCK", name: "Stride Anti-Blister Socks", description: "Breathable running socks with heel lock and seamless toe construction.", category: "running", pricePaise: 39900, costPaise: 10500, inventory: 62, tags: ["running", "socks", "compatible", "anti-blister"], attributes: { size: "free", pack: "2 pairs" }, image: "≈", crossSellIds: ["p_runner"], subscriptionEligible: false, available: true },
  { id: "p_bottle", sku: "NIL-RUN-HYD", name: "Softgrip Hydration Flask", description: "Leak-resistant 500 ml flask shaped for one-hand use while running.", category: "running", pricePaise: 59900, costPaise: 19000, inventory: 37, tags: ["running", "hydration", "compatible"], attributes: { capacity: "500 ml", bpa: "free" }, image: "◒", crossSellIds: ["p_belt"], subscriptionEligible: false, available: true },
  { id: "p_belt", sku: "NIL-RUN-BELT", name: "AirMesh Running Belt", description: "Low-bounce phone and key belt with reflective trim for evening runs.", category: "running", pricePaise: 79900, costPaise: 25500, inventory: 24, tags: ["running", "accessory", "reflective"], attributes: { fit: "adjustable", weather: "splash-resistant" }, image: "⌁", crossSellIds: ["p_bottle"], subscriptionEligible: false, available: true },
  { id: "p_charger", sku: "NIL-TEC-45", name: "GaN Pocket Charger 45W", description: "Compact dual-port charger for phones, tablets and USB-C notebooks.", category: "electronics", pricePaise: 159900, costPaise: 82000, inventory: 31, tags: ["charger", "usb-c", "gan", "travel", "primary"], attributes: { ports: "2", output: "45W", cableIncluded: "no" }, image: "ϟ", crossSellIds: ["p_cable"], subscriptionEligible: false, available: true },
  { id: "p_cable", sku: "NIL-TEC-CBL", name: "Braided USB-C Cable", description: "Two-metre 100W cable compatible with the GaN Pocket Charger.", category: "electronics", pricePaise: 49900, costPaise: 12500, inventory: 85, tags: ["usb-c", "cable", "compatible", "100w"], attributes: { length: "2 m", power: "100W" }, image: "∿", crossSellIds: ["p_charger"], subscriptionEligible: false, available: true }
];

export function searchCatalog(query: string) {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
  return products.filter((product) => [product.name, product.description, product.category, ...product.tags, ...Object.values(product.attributes)].join(" ").toLowerCase().split(" ").some((word) => terms.some((term) => word.includes(term) || term.includes(word)))).sort((a, b) => b.inventory - a.inventory);
}

export const findProduct = (id: string) => products.find((product) => product.id === id);
