import { CommerceState } from "./types";

const transitions: Record<CommerceState, CommerceState[]> = {
  INTENT_RECEIVED: ["CATALOG_SEARCHED", "CANCELLED"], CATALOG_SEARCHED: ["CART_PROPOSED", "CANCELLED"], CART_PROPOSED: ["GROWTH_OPTIMIZED", "PRICE_VERIFIED", "CANCELLED"], GROWTH_OPTIMIZED: ["PRICE_VERIFIED", "CANCELLED"], PRICE_VERIFIED: ["POLICY_EVALUATED", "POLICY_BLOCKED"], POLICY_EVALUATED: ["AWAITING_APPROVAL", "AUTHORIZED", "POLICY_BLOCKED"], AWAITING_APPROVAL: ["AUTHORIZED", "CANCELLED", "EXPIRED"], AUTHORIZED: ["RAZORPAY_ORDER_CREATED", "CANCELLED"], RAZORPAY_ORDER_CREATED: ["CHECKOUT_PENDING", "CANCELLED"], CHECKOUT_PENDING: ["PAYMENT_AUTHORIZED", "PAYMENT_FAILED", "EXPIRED"], PAYMENT_AUTHORIZED: ["PAYMENT_CAPTURED", "PAYMENT_FAILED"], PAYMENT_CAPTURED: ["ORDER_CONFIRMED"], ORDER_CONFIRMED: ["FULFILLMENT_PENDING", "REFUND_REQUESTED"], FULFILLMENT_PENDING: ["COMPLETED", "REFUND_REQUESTED"], COMPLETED: ["REFUND_REQUESTED"], CANCELLED: [], PAYMENT_FAILED: [], POLICY_BLOCKED: [], EXPIRED: [], REFUND_REQUESTED: ["REFUNDED"], REFUNDED: []
};
export function canTransition(from: CommerceState, to: CommerceState) { return transitions[from].includes(to); }
export function transition(from: CommerceState, to: CommerceState) { if (!canTransition(from, to)) throw new Error(`Impossible commerce transition: ${from} → ${to}`); return to; }
