-- Postgres migration for durable AgentReady production mode.
-- Amounts are integer paise. Run through the chosen managed-Postgres migration runner.
create table if not exists merchants (id text primary key, name text not null, created_at timestamptz not null default now());
create table if not exists products (id text primary key, merchant_id text not null references merchants(id), sku text not null, name text not null, description text not null, category text not null, price_paise integer not null check (price_paise >= 0), cost_paise integer not null check (cost_paise >= 0), inventory integer not null check (inventory >= 0), attributes jsonb not null default '{}', metadata jsonb not null default '{}', updated_at timestamptz not null default now(), unique(merchant_id, sku));
create table if not exists agent_sessions (id text primary key, merchant_id text not null references merchants(id), state text not null, request_id text not null, created_at timestamptz not null default now());
create table if not exists mandates (id text primary key, session_id text not null references agent_sessions(id), canonical_payload jsonb not null, canonical_hash text not null, max_amount_paise integer not null, expires_at timestamptz not null, created_at timestamptz not null default now());
create table if not exists carts (id text primary key, session_id text not null references agent_sessions(id), proposed_total_paise integer not null, authoritative_total_paise integer not null, created_at timestamptz not null default now());
create table if not exists cart_items (cart_id text not null references carts(id), product_id text not null references products(id), quantity integer not null check (quantity > 0), unit_price_paise integer not null, primary key(cart_id, product_id));
create table if not exists policy_evaluations (id text primary key, session_id text not null references agent_sessions(id), decision text not null check(decision in ('ALLOW','DENY','REQUIRE_APPROVAL')), reason_codes jsonb not null, authoritative_total_paise integer not null, mandate_hash text not null, created_at timestamptz not null default now());
create table if not exists commerce_orders (id text primary key, session_id text not null references agent_sessions(id), razorpay_order_id text unique, razorpay_payment_id text unique, state text not null, amount_paise integer not null, idempotency_key text not null unique, created_at timestamptz not null default now());
create table if not exists webhook_events (id bigserial primary key, event_hash text not null unique, razorpay_event text not null, razorpay_entity_id text, signature_verified boolean not null, handling_status text not null, received_at timestamptz not null default now());
create table if not exists audit_events (id text primary key, session_id text not null references agent_sessions(id), actor text not null, action text not null, payload jsonb not null, previous_hash text not null, current_hash text not null unique, created_at timestamptz not null default now());
create index if not exists products_merchant_category_idx on products(merchant_id, category);
create index if not exists sessions_merchant_created_idx on agent_sessions(merchant_id, created_at desc);
create index if not exists audit_session_created_idx on audit_events(session_id, created_at);
