import { asc, desc, eq, sql } from "drizzle-orm";
import { createHash, randomUUID } from "crypto";
import { getDb } from "./client";
import { agentSessions, auditEvents, checkoutSessions, commerceOrders, idempotencyRecords, mandates, merchants, products as productsTable, webhookEvents } from "./schema";
import { merchant, products } from "@/lib/catalog";

export async function claimIdempotency(key: string, fingerprint: string) {
  const db = getDb(); if (!db) return { kind: "unavailable" as const };
  const inserted = await db.insert(idempotencyRecords).values({ key, fingerprint, status: "PENDING" }).onConflictDoNothing().returning();
  if (inserted.length) return { kind: "claimed" as const };
  const [existing] = await db.select().from(idempotencyRecords).where(eq(idempotencyRecords.key, key)).limit(1);
  if (!existing) return { kind: "in_progress" as const };
  if (existing.fingerprint !== fingerprint) return { kind: "conflict" as const };
  if (existing.status === "COMPLETED" && existing.response) return { kind: "replay" as const, response: existing.response };
  return { kind: "in_progress" as const, razorpayOrderId: existing.razorpayOrderId };
}
export async function completeIdempotency(key: string, razorpayOrderId: string, response: object) { const db = getDb(); if (!db) return; await db.update(idempotencyRecords).set({ status: "COMPLETED", razorpayOrderId, response, updatedAt: new Date() }).where(eq(idempotencyRecords.key, key)); }
export async function persistCheckoutContext(input: { key: string; requestId: string; mandate: { id: string; canonicalHash: string; maxAmountPaise: number; expiresAt: string }; mandatePayload: object; items: object[]; totalPaise: number; policyDecision: string; reasonCodes: string[]; channel?: string }) { const db = getDb(); if (!db) return null; await seedCatalog(); const stable = createHash("sha256").update(input.key).digest("hex").slice(0, 20); const sessionId = `sess_${stable}`; const checkoutId = `chk_${stable}`; await db.transaction(async tx => { await tx.insert(agentSessions).values({ id: sessionId, merchantId: merchant.id, state: input.policyDecision === "DENY" ? "POLICY_BLOCKED" : "AUTHORIZED", channel: input.channel ?? "web", requestId: input.requestId }).onConflictDoNothing(); await tx.insert(mandates).values({ id: input.mandate.id, sessionId, canonicalPayload: input.mandatePayload, canonicalHash: input.mandate.canonicalHash, maxAmountPaise: input.mandate.maxAmountPaise, expiresAt: new Date(input.mandate.expiresAt), approved: true }).onConflictDoNothing(); await tx.insert(checkoutSessions).values({ id: checkoutId, agentSessionId: sessionId, protocol: input.channel ?? "web", state: input.policyDecision === "DENY" ? "POLICY_BLOCKED" : "AUTHORIZED", lineItems: input.items, authoritativeTotalPaise: input.totalPaise, policyDecision: input.policyDecision, reasonCodes: input.reasonCodes, requestId: input.requestId, idempotencyKey: input.key }).onConflictDoNothing(); }); return { sessionId, checkoutId }; }
export async function persistOrder(input: { razorpayOrderId: string; amountPaise: number; idempotencyKey: string; mandateHash: string; checkoutSessionId?: string }) { const db = getDb(); if (!db) return; await db.insert(commerceOrders).values({ id: `ord_${randomUUID()}`, checkoutSessionId: input.checkoutSessionId, razorpayOrderId: input.razorpayOrderId, state: "RAZORPAY_ORDER_CREATED", amountPaise: input.amountPaise, idempotencyKey: input.idempotencyKey, mandateHash: input.mandateHash }).onConflictDoNothing(); }
export async function persistWebhook(input: { id: string; eventHash: string; event: string; entityId?: string; payload: object }) { const db = getDb(); if (!db) return { duplicate: false }; const inserted = await db.insert(webhookEvents).values({ id: input.id, eventHash: input.eventHash, razorpayEvent: input.event, razorpayEntityId: input.entityId, signatureVerified: true, handlingStatus: "PROCESSED", payload: input.payload }).onConflictDoNothing().returning({ id: webhookEvents.id }); return { duplicate: inserted.length === 0 }; }
export async function seedCatalog() { const db = getDb(); if (!db) return false; await db.insert(merchants).values(merchant).onConflictDoNothing(); for (const product of products) await db.insert(productsTable).values({ id: product.id, merchantId: merchant.id, sku: product.sku, name: product.name, description: product.description, category: product.category, pricePaise: product.pricePaise, costPaise: product.costPaise, inventory: product.inventory, attributes: product.attributes, metadata: { tags: product.tags, crossSellIds: product.crossSellIds, subscriptionEligible: product.subscriptionEligible } }).onConflictDoUpdate({ target: productsTable.id, set: { pricePaise: product.pricePaise, inventory: product.inventory, updatedAt: new Date() } }); return true; }
export async function getOperationalMetrics() { const db = getDb(); if (!db) return null; const orders = await db.select().from(commerceOrders).orderBy(desc(commerceOrders.createdAt)).limit(20); const events = await db.select().from(webhookEvents).orderBy(desc(webhookEvents.receivedAt)).limit(20); const audits = await db.select().from(auditEvents).orderBy(desc(auditEvents.createdAt)).limit(50); return { orders, webhookEvents: events, auditEvents: audits, counts: { testOrders: orders.length, webhookEvents: events.length, auditEvents: audits.length, testOrderValuePaise: orders.reduce((sum, order) => sum + order.amountPaise, 0) } }; }
export async function pingDb() { const db = getDb(); if (!db) return false; try { await db.execute(sql`select 1`); return true; } catch { return false; } }
export async function applyWebhookOrderState(razorpayOrderId: string | undefined, event: string) { const db = getDb(); if (!db || !razorpayOrderId) return; const state = event === "payment.captured" ? "PAYMENT_CAPTURED" : event === "order.paid" ? "ORDER_CONFIRMED" : event === "payment.failed" ? "PAYMENT_FAILED" : event === "payment.authorized" ? "PAYMENT_AUTHORIZED" : null; if (state) await db.update(commerceOrders).set({ state, updatedAt: new Date() }).where(eq(commerceOrders.razorpayOrderId, razorpayOrderId)); }
export async function appendPersistentAudit(input: { sessionId?: string; actor: string; actorType: string; action: string; evidence: object; amountBeforePaise?: number; amountAfterPaise?: number; mandateHash?: string; requestId: string }) { const db = getDb(); if (!db) return null; const [previous] = await db.select({ currentHash: auditEvents.currentHash }).from(auditEvents).orderBy(desc(auditEvents.createdAt)).limit(1); const previousHash = previous?.currentHash ?? "GENESIS"; const id = randomUUID(); const createdAt = new Date(); const payload = { id, sessionId: input.sessionId ?? null, actor: input.actor, actorType: input.actorType, action: input.action, evidence: input.evidence, amountBeforePaise: input.amountBeforePaise ?? null, amountAfterPaise: input.amountAfterPaise ?? null, mandateHash: input.mandateHash ?? null, requestId: input.requestId, createdAt: createdAt.toISOString() }; const currentHash = createHash("sha256").update(`${JSON.stringify(payload)}${previousHash}`).digest("hex"); await db.insert(auditEvents).values({ ...payload, createdAt, previousHash, currentHash }); return { id, previousHash, currentHash }; }
export async function verifyPersistentAudit() { const db = getDb(); if (!db) return { available: false, total: 0, valid: 0, intact: false }; const events = await db.select().from(auditEvents).orderBy(asc(auditEvents.createdAt)); let previousHash = "GENESIS"; let valid = 0; let tamperedIndex: number | null = null; for (let index = 0; index < events.length; index++) { const event = events[index]; const payload = { id: event.id, sessionId: event.sessionId, actor: event.actor, actorType: event.actorType, action: event.action, evidence: event.evidence, amountBeforePaise: event.amountBeforePaise, amountAfterPaise: event.amountAfterPaise, mandateHash: event.mandateHash, requestId: event.requestId, createdAt: event.createdAt.toISOString() }; const expected = createHash("sha256").update(`${JSON.stringify(payload)}${previousHash}`).digest("hex"); if (event.previousHash !== previousHash || event.currentHash !== expected) { tamperedIndex = index; break; } valid++; previousHash = event.currentHash; } return { available: true, total: events.length, valid, intact: valid === events.length, tamperedIndex }; }
