import { randomUUID } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { getCatalogProducts, getCheckoutContext, updateCheckoutContext } from "@/db/repository";
import { evaluatePolicyWithCatalog } from "@/lib/policy";
import type { Mandate } from "@/lib/types";

const version = "2026-04-17";
const patchSchema = z.object({ line_items: z.array(z.object({ product_id: z.string(), quantity: z.number().int().positive().max(10) })).min(1) });
function view(context: NonNullable<Awaited<ReturnType<typeof getCheckoutContext>>>) { return { id: context.checkout.id, state: context.checkout.state, request_id: context.checkout.requestId, line_items: context.checkout.lineItems, authoritative_total_paise: context.checkout.authoritativeTotalPaise, policy: { decision: context.checkout.policyDecision, reasonCodes: context.checkout.reasonCodes }, mandate_hash: context.mandate?.canonicalHash }; }
export async function GET(_: NextRequest, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; const context = await getCheckoutContext(id); return context ? NextResponse.json({ api_version: version, checkout_session: view(context) }) : NextResponse.json({ error: { code: "not_found" } }, { status: 404 }); }
export async function PATCH(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { const { id } = await params; const context = await getCheckoutContext(id); if (!context?.mandate) return NextResponse.json({ error: { code: "not_found" } }, { status: 404 }); const parsed = patchSchema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: { code: "invalid_request" } }, { status: 400 }); const catalog = await getCatalogProducts(parsed.data.line_items.map(item => item.product_id)); const mandate = context.mandate.canonicalPayload as Mandate; let policy; try { policy = evaluatePolicyWithCatalog({ items: parsed.data.line_items.map(item => ({ productId: item.product_id, quantity: item.quantity })), mandate, catalog }); } catch { return NextResponse.json({ error: { code: "invalid_product_id" } }, { status: 400 }); } const state = policy.decision === "DENY" ? "POLICY_BLOCKED" : policy.decision === "REQUIRE_APPROVAL" ? "AWAITING_APPROVAL" : "AUTHORIZED"; await updateCheckoutContext(id, { state, lineItems: parsed.data.line_items, totalPaise: policy.authoritativeTotalPaise, policyDecision: policy.decision, reasonCodes: policy.reasonCodes }); const updated = await getCheckoutContext(id); return NextResponse.json({ api_version: version, checkout_session: updated ? view(updated) : null, request_id: request.headers.get("x-request-id") ?? randomUUID() }); }
