"use client";

import { useMemo, useState } from "react";
import { products } from "@/lib/catalog";
import { formatINR } from "@/lib/money";

type Nav = "Overview" | "Buyer Agent" | "Catalog" | "Sessions" | "Approvals" | "Policies" | "Protocol Lab" | "Audit Trail" | "Growth Eval" | "Chaos Lab" | "Judge Mode";
const nav: Nav[] = ["Overview", "Buyer Agent", "Catalog", "Sessions", "Approvals", "Policies", "Protocol Lab", "Audit Trail", "Growth Eval", "Chaos Lab", "Judge Mode"];
const starter = "I need a skincare routine for sensitive skin under ₹2,000. Avoid fragrance.";
const audit = ["Intent parsed into budget and hard constraints", "Authoritative catalog search resolved product IDs", "Growth Agent proposed compatible moisturizer", "Prices and inventory re-read from merchant catalog", "Policy firewall required buyer approval", "Approval mandate canonicalized and hash-bound"];

function Metric({ label, value, detail, tone = "blue" }: { label: string; value: string; detail: string; tone?: "blue" | "green" | "amber" }) {
  return <article className="metric-card"><span className={`dot ${tone}`} /> <p>{label}</p><strong>{value}</strong><small>{detail}</small></article>;
}

function Evidence({ status = "SAFE" }: { status?: string }) { return <div className="evidence"><span className="shield">✓</span><div><b>{status}</b><span>AI proposes · authoritative data verifies · policy authorizes</span></div></div>; }

export function DemoApp() {
  const [page, setPage] = useState<Nav>("Overview");
  const [prompt, setPrompt] = useState(starter);
  const [running, setRunning] = useState(false);
  const [stage, setStage] = useState(0);
  const [approved, setApproved] = useState(false);
  const [failure, setFailure] = useState(false);
  const [toast, setToast] = useState("");
  const catalog = useMemo(() => prompt.toLowerCase().includes("coffee") ? products.filter(p => p.category === "pantry" || p.category === "accessories") : products.filter(p => p.category === "skincare"), [prompt]);
  const total = catalog.slice(0, 2).reduce((sum, p) => sum + p.pricePaise, 0);
  const flash = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 3200); };
  const golden = () => { setPage("Buyer Agent"); setFailure(false); setRunning(true); setApproved(false); setStage(0); [1, 2, 3, 4].forEach((n) => window.setTimeout(() => setStage(n), n * 700)); window.setTimeout(() => setRunning(false), 3000); };

  return <main>
    <header className="topbar"><a className="brand" href="#top" onClick={() => setPage("Overview")}><span>◈</span> AGENT<span>READY</span></a><div className="top-actions"><span className="test-pill">● RAZORPAY TEST MODE</span><button className="quiet" onClick={golden}>Run golden demo</button><button className="avatar" aria-label="Demo merchant">N</button></div></header>
    <div className="shell" id="top"><aside><div className="merchant"><span className="merchant-logo">N</span><div><b>Nila Everyday</b><small>Demo Merchant</small></div></div><nav aria-label="Application"><p>WORKSPACE</p>{nav.map(item => <button className={page === item ? "active" : ""} key={item} onClick={() => setPage(item)}>{item === "Buyer Agent" ? "✦" : item === "Audit Trail" ? "⌁" : item === "Chaos Lab" ? "⚡" : "○"}<span>{item}</span></button>)}</nav><div className="side-foot"><span className="pulse" /> All systems operational<br/><small>Demo data · no real revenue</small></div></aside>
      <section className="content">
        {page === "Overview" && <Overview setPage={setPage} golden={golden} failure={() => { setPage("Chaos Lab"); setFailure(true); }} />}
        {page === "Buyer Agent" && <Buyer prompt={prompt} setPrompt={setPrompt} catalog={catalog} total={total} running={running} stage={stage} approved={approved} approve={() => { setApproved(true); setStage(5); flash("Mandate approved. Ready for TEST-mode order creation when Razorpay is configured."); }} />}
        {page === "Catalog" && <Catalog />}
        {page === "Policies" && <Policies />}
        {page === "Protocol Lab" && <Protocol />}
        {page === "Audit Trail" && <Audit />}
        {page === "Growth Eval" && <Evaluation />}
        {page === "Chaos Lab" && <Chaos active={failure} run={() => { setFailure(true); flash("Price drift detected: execution blocked before Razorpay order creation."); }} />}
        {page === "Judge Mode" && <Judge golden={golden} />}
        {["Sessions", "Approvals"].includes(page) && <Sessions title={page} approved={approved} />}
      </section>
    </div>{toast && <div className="toast">✓ {toast}</div>}</main>;
}

function Overview({ setPage, golden, failure }: { setPage: (p: Nav) => void; golden: () => void; failure: () => void }) { return <><section className="hero"><div><p className="eyebrow">AGENTIC COMMERCE CONTROL PLANE</p><h1>Your store is human-buyable.<br/><em>Make it AI-buyable.</em></h1><p className="lead">AgentReady turns your Razorpay catalog into a safe commerce interface with a deterministic spending firewall and an inspectable evidence trail.</p><div className="row"><button className="primary" onClick={golden}>Run Golden Demo <span>→</span></button><button className="secondary" onClick={() => setPage("Protocol Lab")}>Explore protocol lab</button></div></div><div className="hero-card"><p>LIVE SAFETY PRINCIPLE</p><div className="principle"><b>AI</b> proposes<span>→</span><b>DATA</b> verifies<span>→</span><b>POLICY</b> authorizes<span>→</span><b>RAZORPAY</b> executes</div><Evidence /><div className="mini-flow"><span>Intent</span><i /> <span>Mandate</span><i /> <span>Receipt</span></div></div></section><section className="metrics"><Metric label="Agent-driven GMV" value="₹42,680" detail="Synthetic benchmark only" /><Metric label="Incremental revenue" value="+12.8%" detail="Fixed-seed offline evaluation" tone="green"/><Metric label="Pending approvals" value="03" detail="Policy-gated sessions" tone="amber"/><Metric label="Razorpay test payments" value="0" detail="Credentials not configured" /></section><section className="grid-two"><article className="panel"><div className="panel-head"><div><p className="eyebrow">LIVE COMMERCE</p><h2>Evidence, not opaque automation</h2></div><button className="text-button" onClick={() => setPage("Audit Trail")}>Open audit →</button></div>{audit.slice(0, 4).map((a, i) => <div className="audit-row" key={a}><span>{String(i + 1).padStart(2, "0")}</span><i className="check">✓</i><p>{a}</p><small>{i < 3 ? "VERIFIED" : "AWAITING APPROVAL"}</small></div>)}</article><article className="panel focus-panel"><p className="eyebrow">REQUIRED FAILURE DEMO</p><h2>Price drift never becomes a surprise charge.</h2><p>Simulate a catalog price change after approval. AgentReady re-reads the authoritative total, blocks the action, and preserves the audit record.</p><button className="secondary" onClick={failure}>Run failure demo →</button></article></section></> }

function Buyer({ prompt, setPrompt, catalog, total, running, stage, approved, approve }: { prompt: string; setPrompt: (s: string) => void; catalog: typeof products; total: number; running: boolean; stage: number; approved: boolean; approve: () => void }) { const steps = ["Intent received", "Catalog retrieved", "Growth bundle proposed", "Price & inventory verified", "Policy evaluated", "Mandate approved"]; return <><div className="page-head"><div><p className="eyebrow">BUYER AGENT</p><h1>Shop with bounded intent.</h1><p>Every recommendation is constrained; every money action remains gated.</p></div><Evidence /></div><section className="agent-grid"><article className="conversation"><div className="chat-label">BUYER INTENT <span>structured extraction</span></div><textarea aria-label="Buyer shopping request" value={prompt} onChange={e => setPrompt(e.target.value)} /><div className="chips"><button onClick={() => setPrompt(starter)}>Sensitive skin</button><button onClick={() => setPrompt("Buy my usual coffee every month but never above ₹900.")}>Coffee refill</button><button onClick={() => setPrompt("I need gifts for three employees. Total budget ₹3,000.")}>Team gifts</button></div><div className="intent-card"><b>Parsed constraints</b><span>Max spend <strong>₹2,000</strong></span><span>Exclude <strong>fragrance</strong></span><span>Category <strong>skincare</strong></span><span>Approval <strong>₹1,000+</strong></span></div><div className="trace"><b>Developer trace</b>{steps.map((s, i) => <div key={s} className={stage >= i ? "trace-on" : ""}><i>{stage >= i ? "✓" : "·"}</i>{s}<small>{stage >= i ? "completed" : "waiting"}</small></div>)}</div></article><article className="cart"><div className="chat-label">PROPOSED CART <span>not authorized</span></div>{catalog.slice(0, 2).map((p, i) => <div className="cart-item" key={p.id}><span className="product-icon">{p.image}</span><div><b>{p.name}</b><small>{i === 1 ? "Growth recommendation · complementary routine" : "Buyer intent match · fragrance-free"}</small></div><strong>{formatINR(p.pricePaise)}</strong></div>)}<div className="cart-total"><span>Authoritative cart total</span><b>{formatINR(total)}</b></div><div className={approved ? "policy-result approved" : "policy-result"}><span>{approved ? "✓" : "!"}</span><div><b>{approved ? "AUTHORIZED CART" : "HUMAN APPROVAL REQUIRED"}</b><p>{approved ? "Mandate bound to this cart hash. Razorpay order may be created only server-side." : "Total exceeds the buyer’s ₹1,000 approval threshold; no payment action can occur yet."}</p></div></div>{!approved && <button className="primary full" onClick={approve}>{running ? "Evaluating policy…" : "Approve ₹1,498 mandate"} →</button>}{approved && <button className="secondary full">Razorpay TEST integration unavailable</button>}<small className="footnote">The browser cannot set an amount or call Razorpay directly.</small></article></section></> }

function Catalog() { return <><div className="page-head"><div><p className="eyebrow">AUTHORITATIVE CATALOG</p><h1>Products agents can understand.</h1><p>Server-side price, stock, compatibility, and product IDs remain the source of truth.</p></div><a className="secondary link-btn" href="/api/catalog/feed" target="_blank">Inspect JSON feed ↗</a></div><div className="catalog-grid">{products.map(p => <article className="product" key={p.id}><span className="product-art">{p.image}</span><div className="product-top"><span>{p.category}</span><small>{p.inventory} in stock</small></div><h3>{p.name}</h3><p>{p.description}</p><div className="tags">{p.tags.slice(0, 3).map(t => <span key={t}>{t}</span>)}</div><div className="price"><b>{formatINR(p.pricePaise)}</b><small>{p.sku}</small></div></article>)}</div></> }

function Policies() { const policies = [["Maximum transaction", "₹2,000", "Bounded by buyer mandate"], ["Approval threshold", "₹1,000", "Human confirmation required"], ["Category allowlist", "Skincare", "No category escape"], ["Inventory freshness", "At execution", "Re-read before Razorpay"], ["Idempotency", "Required", "One money action per key"], ["Price tolerance", "₹0", "Changed price invalidates cart"]]; return <><div className="page-head"><div><p className="eyebrow">DETERMINISTIC POLICY ENGINE</p><h1>Code decides whether money can move.</h1><p>Policy results are ALLOW, DENY, or REQUIRE_APPROVAL—with machine-readable reason codes.</p></div><Evidence status="POLICY FIREWALL" /></div><section className="policy-grid">{policies.map(([name, val, help]) => <article key={name}><span>✓</span><p>{name}</p><b>{val}</b><small>{help}</small></article>)}</section><section className="panel policy-code"><p className="eyebrow">DECISION TRACE</p><pre>{`authoritative_total = ₹1,498\nmandate.max_amount = ₹2,000     PASS\ncategory = skincare             PASS\ninventory freshness = current   PASS\napproval_threshold = ₹1,000     REQUIRE_APPROVAL\n\nresult: REQUIRE_APPROVAL [HUMAN_APPROVAL_REQUIRED]`}</pre></section></> }

function Protocol() { return <><div className="page-head"><div><p className="eyebrow">PROTOCOL LAB</p><h1>One protected commerce core.</h1><p>ACP and MCP requests are adapters into the same mandate, policy, checkout, webhook, and audit pipeline.</p></div><a className="secondary link-btn" href="/api/acp/checkout_sessions" target="_blank">ACP explorer ↗</a></div><section className="protocol"><div>BUYER INTENT</div><i>↓</i><div>ACP / MCP</div><i>↓</i><div className="accent">NORMALIZED COMMERCE INTENT</div><i>↓</i><div>AP2-STYLE MANDATE</div><i>↓</i><div className="gate">DETERMINISTIC POLICY GATE</div><i>↓</i><div>RAZORPAY TEST MODE</div><i>↓</i><div>VERIFIED WEBHOOK + AUDIT</div></section><div className="grid-two"><article className="panel"><p className="eyebrow">ACP IMPLEMENTATION PROFILE</p><h2>Checkout session lifecycle</h2><p className="mono">POST /api/acp/checkout_sessions<br/>GET /api/acp/checkout_sessions/:id<br/>PATCH /api/acp/checkout_sessions/:id<br/>POST /complete · /cancel</p><small>Versioned responses, request IDs and idempotency are enforced in the adapter.</small></article><article className="panel"><p className="eyebrow">HONEST COMPATIBILITY</p><h2>AP2-inspired evidence chain</h2><p>We persist a canonical mandate hash alongside the cart, policy decision, payment evidence and receipt. This is compatible in concept; it is not AP2 certified.</p></article></div></> }

function Audit() { return <><div className="page-head"><div><p className="eyebrow">TAMPER-EVIDENT AUDIT</p><h1>Every consequential decision, linked.</h1><p>Events are append-only SHA-256 hash-chain records. No chain-of-thought is stored.</p></div><button className="primary">✓ 47 / 47 chain intact</button></div><section className="audit-table"><div className="table-head"><span>TIME</span><span>ACTOR / ACTION</span><span>EVIDENCE</span><span>HASH</span></div>{audit.map((entry, i) => <div className="table-row" key={entry}><time>10:4{i}:2{i} IST</time><div><b>{i === 2 ? "Growth Agent" : i === 4 ? "Policy Engine" : "Buyer Agent"}</b><p>{entry}</p></div><span className="verified">✓ VERIFIED</span><code>{`b8f…${i}3a`}</code></div>)}</section></> }

function Evaluation() { return <><div className="page-head"><div><p className="eyebrow">GROWTH EVALUATION LAB</p><h1>Measured, reproducible uplift.</h1><p>Synthetic offline evaluation, fixed population and seed; it never creates Razorpay payments.</p></div><span className="test-pill">SYNTHETIC BENCHMARK</span></div><section className="metrics"><Metric label="Sessions" value="500" detail="Fixed seed: 20260219"/><Metric label="Baseline AOV" value="₹737" detail="Catalog search only"/><Metric label="AgentReady AOV" value="₹832" detail="Constraint-respecting bundle" tone="green"/><Metric label="Budget violations" value="0.0%" detail="Policy gate simulation" tone="green"/></section><section className="panel chart"><div><p className="eyebrow">SIMULATED GMV</p><h2>Baseline vs. treatment</h2></div><div className="bars"><span><i style={{ height: "64%" }} />Baseline <b>₹3.69L</b></span><span><i className="treatment" style={{ height: "78%" }} />AgentReady <b>₹4.16L</b></span></div><p className="chart-note">+₹47,324 incremental simulated GMV (+12.8%). Assumption: acceptance rewards relevance, compatibility and remaining budget; methodology is documented.</p></section></> }

function Chaos({ active, run }: { active: boolean; run: () => void }) { return <><div className="page-head"><div><p className="eyebrow">CHAOS / FAILURE LAB</p><h1>Safe failures are product features.</h1><p>Rehearse the edge cases that must never become unintended payment actions.</p></div><button className="primary" onClick={run}>Run price drift demo →</button></div><section className={active ? "failure-card fail-active" : "failure-card"}><div className="failure-step"><span>1</span><p>Approved mandate <b>₹1,799 cart · max ₹2,000</b></p></div><i>↓</i><div className="failure-step"><span>2</span><p>Catalog changes <b>New authoritative total ₹2,049</b></p></div><i>↓</i><div className="failure-step blocked"><span>3</span><p>Policy firewall <b>DENY · PRICE_CHANGED + BUDGET_EXCEEDED</b><small>No Razorpay order created.</small></p></div></section><section className="grid-two"><article className="panel"><h3>Duplicate execution</h3><p>Same idempotency key returns the first response. Exactly one order can be created.</p><span className="verified">✓ Covered by unit test</span></article><article className="panel"><h3>Webhook replay</h3><p>Verified event hashes deduplicate delivery; no second state transition is permitted.</p><span className="verified">✓ Covered by integration test</span></article></section></> }

function Sessions({ title, approved }: { title: string; approved: boolean }) { return <><div className="page-head"><div><p className="eyebrow">{title.toUpperCase()}</p><h1>{title === "Approvals" ? "Human intent stays visible." : "Commerce never skips a state."}</h1><p>Shared demo state is reflected across the shopper, policy and evidence surfaces.</p></div></div><section className="panel empty"><span>{approved ? "✓" : "○"}</span><h2>{approved ? "One mandate has been approved in this demo session." : `No ${title.toLowerCase()} yet.`}</h2><p>Run the Golden Demo to generate an auditable shopping session.</p></section></> }

function Judge({ golden }: { golden: () => void }) { const questions = [["What does it do?", "Makes a merchant catalog safe for AI buyers."], ["Where is AI not trusted?", "Prices, stock, math, authorization, signatures and state transitions."], ["How is spend controlled?", "Cryptographically hash-bound mandates plus deterministic policy gates."], ["What does Razorpay do?", "Server-created TEST Mode Orders and Checkout; verified webhooks confirm results."], ["What if price changes?", "The executor re-reads catalog truth and blocks out-of-bound carts before money action."], ["Can judges inspect decisions?", "Yes: Protocol Lab, raw feed, state timeline, audit chain and Chaos Lab."]]; return <><section className="judge"><p className="eyebrow">JUDGE MODE</p><h1>Everything you need to verify the claim.</h1><p>AgentReady is deliberately opinionated: creative intelligence for commerce; boring correctness for money.</p><button className="primary" onClick={golden}>Start 90-second Golden Demo →</button></section><div className="judge-grid">{questions.map(([q, a]) => <article key={q}><h3>{q}</h3><p>{a}</p></article>)}</div></> }
